# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-19 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190319_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dummy-person.jpg', upload_to='profile_pics'),
        ),
    ]
