# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-21 15:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190321_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
