# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190321_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editor',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
