# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-21 16:00
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editor',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
