# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-21 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190321_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='editor',
        ),
    ]
