# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-21 17:07
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_profile_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editor',
            field=froala_editor.fields.FroalaField(blank=True, default=''),
        ),
    ]
